MinStat.Enterprises.WebUI/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MinStat.Enterprises.WebUI.Filters;

namespace MinStat.Enterprises.WebUI.Controllers
{
    using MinStat.Enterprises.WebUI.ServiceAdapters;
    using MinStat.Enterprises.WebUI.Models;

    [Authorize, NoCache]
    public class PeopleController : Controller
    {
        private IEnterpriseServiceAdapter _enterpriseAdapter;

        public PeopleController(IEnterpriseServiceAdapter enterpriseServiceAdapter)
        {
            _enterpriseAdapter = enterpriseServiceAdapter;
        }

        public PeopleController()
            : this(new EnterpriseServiceAdapter())
        {
            
        }

        public ActionResult Index(int summaryId = 0, int page = 1, string orderby = "Title")
        {
            if (summaryId == 0) return RedirectToAction("Index", "Summaries");
            if (page < 1) page = 1;

            PeopleModel model = new PeopleModel();
            if (summaryId != 0)
            {
                model.Published = _enterpriseAdapter.IsPublished(summaryId);
            }
            model.Page = page;
            model.SummaryId = summaryId;
            model.OrderBy = orderby;
            model.Direction = orderby.EndsWith("Desc", StringComparison.OrdinalIgnoreCase) ? "" : " Desc";
            model.PageSize = Int32.Parse(ConfigurationManager.AppSettings["peoplepagesize"]);
            model.Count = _enterpriseAdapter.GetPeopleCount(summaryId);
            model.PersonModels = _enterpriseAdapter.GetPeople(summaryId, model.PageSize, (page - 1) * model.PageSize, orderby);
            return View(model);
        }

        public PartialViewResult Edit(int summaryId)
        {
            PersonModel model = new PersonModel();
            model.SummaryId = summaryId;
            ViewBag.EducationLevels = _enterpriseAdapter.GetEducationLevels();
            ViewBag.PostLevels = _enterpriseAdapter.GetPostLevels();
            ViewBag.Activities = _enterpriseAdapter.GetActivities(summaryId);
            return this.PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(PersonModel model, string button)
        {
            ViewBag.EducationLevels = _enterpriseAdapter.GetEducationLevels();
            ViewBag.PostLevels = _enterpriseAdapter.GetPostLevels();
            ViewBag.Activities = _enterpriseAdapter.GetActivities(model.SummaryId);
            if (button.Equals("Удалить", StringComparison.OrdinalIgnoreCase))
            {
                _enterpriseAdapter.RemovePerson(model.Id);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    if (model.Id == 0)
                    {
                        _enterpriseAdapter.CreatePerson(model);
                    }
                    else
                    {
                        _enterpriseAdapter.UpdatePerson(model);
                    }
                }
            }
            HttpContext.Response.Redirect(HttpContext.Request.Url.AbsoluteUri);
            return this.PartialView(model);
        }



    }
}

MinStat.Enterprises.WebUI/Controllers/SummariesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MinStat.Enterprises.WebUI.Filters;
using MinStat.Enterprises.WebUI.ServiceAdapters;
using MinStat.Enterprises.WebUI.Models;

namespace MinStat.Enterprises.WebUI.Controllers
{
    [Authorize, NoCache]
    public class SummariesController : Controller
    {
        //
        // GET: /Summaries/
        private IEnterpriseServiceAdapter _serviceAdapter;
        private string _enterpriseName;

        public SummariesController(IEnterpriseServiceAdapter serviceAdapter)
        {
            _serviceAdapter = serviceAdapter;
            //ToDo: Разобраться, почему не ловится ошибка.
            try
            {
                _enterpriseName = _serviceAdapter.GetEnterpriseName();
                ViewBag.EnterpriseName = _enterpriseName;
                ViewBag.FederalSubjectName = _serviceAdapter.GetFederalSubjectName();
                ViewBag.FederalDistrictName = _serviceAdapter.GetFederalDistrictName();
            }
            catch(Exception)
            {}
        }

        public SummariesController()
            : this(new EnterpriseServiceAdapter())
        {
        }

        public ActionResult Index()
        {
            IEnumerable<SummaryModel> model = _serviceAdapter.GetSummaries();
            ViewBag.Activities = _serviceAdapter.GetActivities();
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Create(SummaryModel summary)
        {
            if (!String.IsNullOrWhiteSpace(summary.Title))
            {
                if (summary.Id > 0)
                {
                    _serviceAdapter.UpdateSummary(summary.Id, summary.Title, summary.Activities);
                }
                else
                {
                    _serviceAdapter.CreateSummary(summary.Title, summary.Activities);

                }
            }
            else
            {
                ModelState.AddModelError("", "Укажите название отчета.");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Remove(int summaryId)
        {
            _serviceAdapter.RemoveSummary(summaryId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Copy(string Title, int summaryId)
        {
            _serviceAdapter.CopySummary(Title, summaryId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Publish(int summaryId)
        {
            _serviceAdapter.PublishSummary(summaryId);
            return RedirectToAction("Index");
        }

        public JsonResult Activities(int summaryId)
        {
            IEnumerable<ActivityModel> activities = _serviceAdapter.GetActivities(summaryId);
            return Json(activities, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> fileUpload, int summaryId)
        {
            try
            {
                foreach (var file in fileUpload)
                {
                    if (file == null) continue;

                    byte[] fileByteArray = new byte[file.InputStream.Length];
                    file.InputStream.Read(fileByteArray, 0, fileByteArray.Length);
                    _serviceAdapter.UploadPersons(fileByteArray, summaryId);
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("uploadfail", "При загрузке файла произошла ошибка. Проверьте загружаемый файл на валидность данных.");
                return Index();
            }

        }

    }
}

MinStat.Enterprises.WebUI/Views/Summaries/Index.cshtml
@using MinStat.Enterprises.WebUI.Models
@model IEnumerable<SummaryModel>
@{
    ViewBag.Title = "Index";
}
<script src="@Url.Content("~/Scripts/Bonch.Enterprises.Summary.js")" type="text/javascript" ></script>
@Html.ValidationSummary()
<div class="row">
    <div class="span10 offset1">
        <h4>@ViewBag.FederalDistrictName</h4>
        <h4>@ViewBag.FederalSubjectName</h4>
        <h3>@ViewBag.EnterpriseName</h3>
        <br />
        <table class="table">
            @foreach (SummaryModel summaryItem in Model)
            {
                <tr>
                    <td>@summaryItem.CreateDate
                    </td>
                    <td>@summaryItem.Title
                    </td>
                    <td>@summaryItem.PublishedDate
                    </td>
                    <td>
                        @Html.ActionLink("Люди", "Index", "People", new { summaryId = summaryItem.Id }, new { @class = "btn btn-primary" })
                    </td>
                    <td>
                        @using (Html.BeginForm(new { controller = "Summaries", action = "Copy", summaryId = @summaryItem.Id }))
                        {
                            <a class="btn btn-primary" data-toggle="modal" href="@String.Format("#activityModalCopy{0}", summaryItem.Id)">
                                Копировать</a>
                            <br />
                            <div class="modal hide" name="@String.Format("activityModalCopy{0}", summaryItem.Id)" id="@String.Format("activityModalCopy{0}", summaryItem.Id)">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">
                                        ×</button>
                                    <h3>
                                        Новый отчет</h3>
                                </div>
                                <div class="modal-body">
                                    <div class="alert alert-error" name="@String.Format("emptytitleerror{0}", summaryItem.Id)" id="@String.Format("emptytitleerror{0}", summaryItem.Id)">
                                        <button class="close" data-dismiss="alert">
                                            ×</button>
                                        <strong>Ошибка!</strong> Укажите пожалуйста название отчета.
                                    </div>
                                    <input type="text" class="input-xlarge" name="Title" />
                                </div>
                                <div class="modal-footer">
                                    <a href="#" class="btn" data-dismiss="modal">Отмена</a>
                                    <input type="submit" id="@String.Format("savesummary{0}", summaryItem.Id)" name="@String.Format("savesummary{0}", summaryItem.Id)" class="btn btn-primary" value="Копировать" />
                                </div>
                            </div>
                        }
                    </td>
                    <td>
                        @if (!summaryItem.Published)
                        {
                            <a class="btn btn-primary uploadcsv">Загрузить</a>
                            using (Html.BeginForm("Upload", "Summaries", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                            <input type="hidden" name="summaryId" id="summaryId" value="@summaryItem.Id"/>
                            <div class="modal hide" id="uploadcsvmodal">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">
                                        ×</button>
                                    <h3>
                                        Загрузка файла</h3>
                                </div>
                                <div class="modal-body">
                                    <p>
                                        <input type="file" name="fileUpload" class="btn btn-primary" /></p>
                                </div>
                                <div class="modal-footer">
                                    <a href="#" class="btn" data-dismiss="modal">Отмена</a>
                                    <input type="submit" class="btn btn-primary" value="Загрузить" />
                                </div>
                            </div>
                            }
                        }
                        else
                        {
                            <input type="submit" class="btn btn-inverse disabled" value="Загрузить" />
                        }
                    </td>
                    <td>
                        @if (!summaryItem.Published)
                        {
                            <a class="btn btn-primary changeactivities" summary-id="@summaryItem.Id" summary-title="@summaryItem.Title">
                                Редактировать</a>
                        }
                        else
                        {
                            <input type="submit" class="btn btn-inverse disabled" value="Редактировать" />
                        }
                    </td>
                    <td>
                        @if (!summaryItem.Published)
                        {
                            <a class="btn btn-warning activityModalPublish" data-toggle="modal" href="#activityModalPublish" data-value="@summaryItem.Id">
                                Опубликовать</a>
                        }
                        else
                        {
                            <input type="submit" class="btn btn-inverse disabled" value="Опубликовать" />
                        }
                    </td>
                    <td style="">
                        @if (!summaryItem.Published)
                        {
                            using (Html.BeginForm(new { controller = "Summaries", action = "Remove", summaryId = @summaryItem.Id }))
                            {
                            <input type="submit" class="btn btn-danger" value="Удалить" />
                            }
                        }
                        else
                        {
                            <input type="submit" class="btn btn-inverse disabled" value="Удалить" />
                        }
                    </td>
                </tr>
            }
        </table>
        <div class="modal hide" name="activityModalPublish" id="activityModalPublish">
            <div class="modal-header">
                <a type="button" class="close" data-dismiss="modal">×</a>
                <h3>
                    Публикация отчета</h3>
            </div>
            <div class="modal-body">
                Вы уверены, что хотите опубликовать отчет? После публикации, внесение любых изменений
                станет невозможным.
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Publish", "Summaries"))
                {
                    <a href="#" class="btn" data-dismiss="modal">Отмена</a>
                    <input type="hidden" id="summaryId" name="summaryId" />
                    <input type="submit" class="btn btn-primary" value="Опубликовать" />
                }
            </div>
        </div>
        @using (Html.BeginForm("Create", "Summaries"))
        {
            <a class="btn changeactivities" summary-id="0" summary-title="">Создать новый отчет</a>
            <br />
            <div class="modal hide" name="activityModal0" id="activityModal0">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        ×</button>
                    <h3>
                        Новый отчет</h3>
                </div>
                <div class="modal-body">
                    <div class="alert alert-error" name="emptytitleerror0" id="emptytitleerror0">
                        <button class="close" data-dismiss="alert">
                            ×</button>
                        <strong>Ошибка!</strong> Укажите пожалуйста название отчета.
                    </div>
                    Введите название отчета: <input type="text" class="input-xlarge" name="Title" id="Title" />
                    <input type="hidden" id="summaryId" name="summaryId" />
                    <table class="table">
                        @foreach (ActivityModel activity in (IEnumerable<ActivityModel>)ViewBag.Activities)
                        {
                            <tr style='@Html.Raw(activity.Part_5 == 0 ? "font-weight:bold;" : "")'>
                                <td>
                                    @String.Format("{0}.{1}{2}.{3}{4}", activity.Part_1, activity.Part_2, activity.Part_3, activity.Part_4, activity.Part_5)
                                </td>
                                <td>
                                    @activity.Title
                                </td>
                                <td>
                                    @if (activity.Part_5 != 0)
                                    {
                                        <input type="checkbox" id="@String.Format("Activity{0}", activity.Id)" name="@String.Format("Activity{0}", activity.Id)" />
                                    }
                                </td>
                            </tr>
                        }
                    </table>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn" data-dismiss="modal">Отмена</a>
                    <input type="submit" id="savesummary0" name="savesummary0" class="btn btn-primary"
                        value="Далее">
                </div>
            </div>
        }
    </div>
</div>