MinStat.AnalizeUI/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinStat.AnalizeUI.Controllers
{
    using Models;
    using ServiceAdapters;

    public class CommonController : Controller
    {
        private readonly FastSummaryReportAdapter _adapter;
        private IInfoDataAdapter _infoAdapter;

        public CommonController()
        {
            _adapter = new FastSummaryReportAdapter();
            _infoAdapter = new InfoDataAdapter();
        }

        //ToDo: Оптимизировать получение данных об округе, субъекте и предприятии
        public ActionResult Report(int? enterpriseId, int? federalSubjectId, int? federalDistrictId, int? activityId)
        {
            IEnumerable<StatisticDataModel> statisticData = _adapter.GetFastSummaryReport(enterpriseId ?? 0, federalSubjectId ?? 0, federalDistrictId ?? 0, activityId ?? 0);

            foreach (StatisticDataModel model in statisticData)
            {
                model.MainActivity = "Связи, информационных технологий и массовых коммуникаций";
                model.ReportName = "Стандартный";
                model.CreatedDateTime = String.Format("{0} {1}", DateTime.Now.ToShortDateString(), DateTime.Now.ToShortTimeString());
                model.Activity = activityId == null ? "Все виды деятельности" : _infoAdapter.GetActivities().Single(x => x.Id == activityId).Title;
                model.FederalDistrict = federalDistrictId == null
                                            ? "Все Федеральные округа"
                                            : _infoAdapter.GetFederalDistricts().Single(x => x.Id == federalDistrictId)
                                                  .Title;

                if (federalSubjectId == null)
                {
                    model.FederalSubject = "Все субъекты федерации";
                }
                else
                {
                    FederalSubjectModel federalSubject =
                        _infoAdapter.GetFederalSubjects(0).Single(x => x.Id == federalSubjectId);
                    model.FederalSubject = federalSubject.Title;
                    model.FederalDistrict =
                        _infoAdapter.GetFederalDistricts().Single(x => x.Id == federalSubject.FederalDistrictId).Title;
                }

                if (enterpriseId == null)
                {
                    model.Enterprise = "Все предприятия";
                }
                else
                {
                    EnterpriseModel enterprise = _infoAdapter.GetEnterprises(0).Single(x => x.Id == enterpriseId);
                    model.Enterprise = enterprise.Title;
                    FederalSubjectModel federalSubject =
                       _infoAdapter.GetFederalSubjects(0).Single(x => x.Id == enterprise.FederalSubjectId);
                    model.FederalSubject = federalSubject.Title;
                    model.FederalDistrict =
                        _infoAdapter.GetFederalDistricts().Single(x => x.Id == federalSubject.FederalDistrictId).Title;
                }
            }

            return View("StaticStatisticData", statisticData);
        }

        public ActionResult Chooser()
        {
            FastSummarySelectModel model = new FastSummarySelectModel();
            model.Activities = _infoAdapter.GetActivities();
            model.Enterprises = _infoAdapter.GetEnterprises(0);
            model.FederalSubjects = _infoAdapter.GetFederalSubjects(0);
            model.FederalDistricts = _infoAdapter.GetFederalDistricts();
            return PartialView(model);
        }

    }
}

MinStat.AnalizeUI/Controllers/FullReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MinStat.AnalizeUI.Filters;
using MinStat.AnalizeUI.O;
using MinStat.AnalizeUI.ServiceAdapters;
using MinStat.AnalizeUI.Models;
using System.Text;

namespace MinStat.AnalizeUI.Controllers
{
    [NoCache]
    public class FullReportController : Controller
    {
        //
        // GET: /FullReport/
        private readonly FullReportAdapter _adapter;
        private readonly SelectionReportAdapter _selectionReport;
        private readonly InfoDataAdapter _infoAdapter;

        public FullReportController()
        {
            _adapter = new FullReportAdapter();
            _selectionReport = new SelectionReportAdapter();
            _infoAdapter = new InfoDataAdapter();

            Dictionary<int, string> federalDistricts = _infoAdapter.GetFederalDistricts().ToDictionary(x => x.Id, x => x.Title);
            federalDistricts.Add(0, "Все округа");
            ViewBag.FederalDistricts = federalDistricts.OrderBy(x => x.Key);
            ViewBag.StartDate = new DateTime(DateTime.Now.Year, 1, 1).ToShortDateString();
            ViewBag.EndDate = DateTime.Now.ToShortDateString();
            ViewBag.FullReport = "active";
            ViewBag.Consolidate = "";
            ViewBag.Summary = "";
            ViewBag.Administration = "";
            ViewBag.Help = "";
        }

        public ActionResult Index()
        {
            IEnumerable<StatisticDataModel> model = new StatisticDataModel[0];
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(int? enterpriseId, int? federalSubjectId, int? federalDistrictId, string startDate, string endDate)
        {
            Session["enterpriseId"] = enterpriseId ?? 0;
            Session["federalSubjectId"] = federalSubjectId ?? 0;
            Session["federalDistrictId"] = federalDistrictId ?? 0;
            Session["startDate"] = startDate;
            Session["endDate"] = endDate;

            IEnumerable<StatisticDataModel> model = _adapter.GetFullReport(enterpriseId ?? 0, federalSubjectId ?? 0, federalDistrictId ?? 0,
                                                              DateTime.Parse(startDate), DateTime.Parse(endDate));
            ViewBag.StartDate = startDate;
            ViewBag.EndDate = endDate;
            ViewBag.SelectedFederalSubjectId = federalSubjectId ?? 0;
            ViewBag.SelectedEnterpriseId = enterpriseId ?? 0;
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult CustomReport(SelectionChecks selectionChecks, string reportType)
        {
            if (!selectionChecks.HorizontalChecks.Any() || !selectionChecks.VerticalChecks.Any())
            {
                ModelState.AddModelError("nochecks", "Для составления отчета необходимо указать виды деятельности и категории работников!");
                return Index((int?)Session["enterpriseId"], (int?)Session["federalSubjectId"], (int?)Session["federalDistrictId"],
                             (string)Session["startDate"], (string)Session["endDate"]);
            }

            ViewBag.RenderGraphic = true;
            IEnumerable<StatisticDataModel> model = new StatisticDataModel[0];
            FillReportMetaData(model, selectionChecks.VerticalChecks, selectionChecks.HorizontalChecks);
            if (reportType.EndsWith("#static") || String.IsNullOrWhiteSpace(reportType))
            {
                Session["startDate"] = null;
                DateTime startDate = new DateTime(DateTime.Parse((string)Session["endDate"]).Year, 1, 1);
                model = _selectionReport.GetQtyStaticData(
                    (int)Session["enterpriseId"],
                    (int)Session["federalSubjectId"],
                    (int)Session["federalDistrictId"],
                    startDate.ToShortDateString(),
                    (string)Session["endDate"],
                    selectionChecks.VerticalChecks, selectionChecks.HorizontalChecks);
                FillReportMetaData(model, selectionChecks.VerticalChecks, selectionChecks.HorizontalChecks);
                return View("StaticStatisticData", model);
            }
            if (reportType.EndsWith("#dynamic"))
            {
                model = _selectionReport.GetQtyDynamicData(
                    (int)Session["enterpriseId"],
                    (int)Session["federalSubjectId"],
                    (int)Session["federalDistrictId"],
                    (string)Session["startDate"],
                    (string)Session["endDate"],
                    selectionChecks.VerticalChecks, selectionChecks.HorizontalChecks);
                FillReportMetaData(model, selectionChecks.VerticalChecks, selectionChecks.HorizontalChecks);
                return View("DynamicStatisticData", model);
            }
            FillReportMetaData(model, selectionChecks.VerticalChecks, selectionChecks.HorizontalChecks);
            return View("Index", model);
        }

        private void FillReportMetaData(IEnumerable<StatisticDataModel> model, List<int> selectedActivities, List<KeyValuePair<int, int>> selectedGroups)
        {
            foreach (StatisticDataModel eModel in model)
            {
                eModel.MainActivity = "Связи, информационных технологий и массовых коммуникаций";
                eModel.ReportName = "Базовый";
                eModel.CreatedDateTime = String.Format("{0} {1}", DateTime.Now.ToShortDateString(),
                                                       DateTime.Now.ToShortTimeString());

                var activityTitles = _infoAdapter.GetActivities()
                   .Where(x => selectedActivities.Contains(x.Id) && x.Part_5 != 0)
                   .Select(x => x.Title);

                var educationLevels = _infoAdapter.GetEducationLevels();
                var postLevels = _infoAdapter.GetPostLevels();

                StringBuilder groupsTitlesStringBuilder = new StringBuilder();
                foreach (KeyValuePair<int, int> group in selectedGroups)
                {
                    groupsTitlesStringBuilder.AppendFormat("<div style=\"padding-left:20px;\">{0}_{1}</div>", 
                        postLevels.First(x => x.Key == group.Key).Value, 
                        educationLevels.First(x => x.Key == group.Value).Value);
                }

                eModel.Categories = groupsTitlesStringBuilder.ToString();

                StringBuilder activityTitlesStringBuilder = new StringBuilder();

                foreach (var activityTitle in activityTitles)
                {
                    activityTitlesStringBuilder.AppendFormat("<div style=\"padding-left:20px;\">{0}</div>", activityTitle);
                }

                eModel.Activity = activityTitlesStringBuilder.ToString();

                eModel.StartDate = (string) Session["startDate"];
                eModel.EndDate = (string)Session["endDate"];
                eModel.FederalDistrict = (int) Session["federalDistrictId"] == 0
                                             ? "Все Федеральные округа"
                                             : _infoAdapter.GetFederalDistricts().Single(
                                                 x => x.Id == (int) Session["federalDistrictId"])
                                                   .Title;

                if ((int) Session["federalSubjectId"] == 0)
                {
                    eModel.FederalSubject = "Все субъекты федерации";
                }
                else
                {
                    FederalSubjectModel federalSubject =
                        _infoAdapter.GetFederalSubjects(0).Single(x => x.Id == (int) Session["federalSubjectId"]);
                    eModel.FederalSubject = federalSubject.Title;
                    eModel.FederalDistrict =
                        _infoAdapter.GetFederalDistricts().Single(x => x.Id == federalSubject.FederalDistrictId).Title;
                }

                if ((int) Session["enterpriseId"] == 0)
                {
                    eModel.Enterprise = "Все предприятия";
                }
                else
                {
                    EnterpriseModel enterprise =
                        _infoAdapter.GetEnterprises(0).Single(x => x.Id == (int) Session["enterpriseId"]);
                    eModel.Enterprise = enterprise.Title;
                    FederalSubjectModel federalSubject =
                        _infoAdapter.GetFederalSubjects(0).Single(x => x.Id == enterprise.FederalSubjectId);
                    eModel.FederalSubject = federalSubject.Title;
                    eModel.FederalDistrict =
                        _infoAdapter.GetFederalDistricts().Single(x => x.Id == federalSubject.FederalDistrictId).Title;
                }
            }
        }
    }
}

MinStat.AnalizeUI/Controllers/HelpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinStat.AnalizeUI.Controllers
{
    public class HelpController : Controller
    {
        public HelpController()
        {
            ViewBag.FullReport = "";
            ViewBag.Consolidate = "";
            ViewBag.Summary = "";
            ViewBag.Administration = "";
            ViewBag.Help = "active";
        }

        public ActionResult Index()
        {
            return View();
        }

    }
}

MinStat.AnalizeUI/Controllers/SummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MinStat.AnalizeUI.Models;
using MinStat.AnalizeUI.ServiceAdapters;

namespace MinStat.AnalizeUI.Controllers
{
    public class SummaryController : Controller
    {
        private IInfoDataAdapter _infoAdapter;
        private SummaryReportAdapter _summaryAdapter;

        public SummaryController()
        {
            _infoAdapter = new InfoDataAdapter();
            _summaryAdapter = new SummaryReportAdapter();

            Dictionary<int, string> federalDistricts = _infoAdapter.GetFederalDistricts().ToDictionary(x => x.Id, x => x.Title);
            federalDistricts.Add(0, "Все округа");
            ViewBag.FederalDistricts = federalDistricts.OrderBy(x => x.Key);
            ViewBag.EndDate = DateTime.Now.ToShortDateString();
            ViewBag.FullReport = "";
            ViewBag.Consolidate = "";
            ViewBag.Summary = "active";
            ViewBag.Administration = "";
            ViewBag.Help = "";
        }

        public ActionResult Index()
        {
            SummaryReportCreatorModel model = new SummaryReportCreatorModel();
            model.Activities = _infoAdapter.GetActivities();
            model.EducationLevels = _infoAdapter.GetEducationLevels();
            model.PostLevels = _infoAdapter.GetPostLevels();
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(SummaryReportCreatorModel model)
        {
            if (!model.SelectedActivities.Any()
                || !model.SelectedGenders.Any()
                || !model.SelectedEducationLevels.Any()
                ||!model.SelectedPostLevels.Any()
                )
            {
                ModelState.AddModelError("activities", "Необходимо указать виды деятельности.");
                ModelState.AddModelError("genders", "Необходимо указать пол.");
                ModelState.AddModelError("educationlevels", "Необходимо указать уровни образования.");
                ModelState.AddModelError("postlevels", "Необходимо указать категории работников.");
            }

            if (!ModelState.IsValid) { return Index(); }

            IEnumerable<StatisticDataModel> statisticData = _summaryAdapter.GetSummaryReport(model);
            foreach (StatisticDataModel eModel in statisticData)
            {
                eModel.MainActivity = "Связи, информационных технологий и массовых коммуникаций";
                eModel.ReportName = "Количественный";
                eModel.CreatedDateTime = String.Format("{0} {1}", DateTime.Now.ToShortDateString(), DateTime.Now.ToShortTimeString());
                eModel.FederalDistrict = model.FederalDistrictId == 0
                                            ? "Все Федеральные округа"
                                            : _infoAdapter.GetFederalDistricts().Single(x => x.Id == model.FederalDistrictId)
                                                  .Title;

                if (model.FederalSubjectId == 0)
                {
                    eModel.FederalSubject = "Все субъекты федерации";
                }
                else
                {
                    FederalSubjectModel federalSubject =
                        _infoAdapter.GetFederalSubjects(0).Single(x => x.Id == model.FederalSubjectId);
                    eModel.FederalSubject = federalSubject.Title;
                }

                if (model.EnterpriseId == 0)
                {
                    eModel.Enterprise = "Все предприятия";
                }
                else
                {
                    EnterpriseModel enterprise = _infoAdapter.GetEnterprises(0).Single(x => x.Id == model.EnterpriseId);
                    eModel.Enterprise = enterprise.Title;
                }
            }

            return View("StaticStatisticData", statisticData);
        }

    }
}

MinStat.AnalizeUI/Views/Shared/DynamicDiagram.cshtml
@using System.Text
@using MinStat.AnalizeUI.Models
@model StatisticDataModel
@{ Model.Values = Model.Values.Where(x => x.BoldLevel == 0).ToList(); }
<script type="text/javascript" src="@Url.Content("~/Scripts//plugins/jqplot.barRenderer.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts//plugins/jqplot.categoryAxisRenderer.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts//plugins/jqplot.pointLabels.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts//plugins/jqplot.enhancedLegendRenderer.min.js")"></script>
<script type="text/javascript">
    $(document).ready(function () {
        
        @helper Vars(IEnumerable<string> values)
            {
            @Html.Raw(values.Aggregate((x, y) => String.Format("{0},{1}", x, y)))
        }
        
        @helper Series(IEnumerable<string> values)
        {
            StringBuilder sb = new StringBuilder();
            foreach (var value in values)
            {
                sb.Append(" { label: '"+value+"'  },");
            }
            @Html.Raw(sb.ToString());
        }
        @foreach (StatisticDataItemModel dataItem in Model.Values)
        {
            @Html.Raw(String.Format("var points{0} = [];", dataItem.Id));
                                                                        foreach (string value in dataItem.Values)
                                                                        {
                @Html.Raw(String.Format("points{0}.push({1});", dataItem.Id, value.Replace(",", ".")));
                                                                        }

        }

        var plot3 = $.jqplot('chart3', [@Vars(Model.Values.Select(x => "points" + x.Id))],
    {
        series: [@Series(Model.Values.Select(x => x.Title))],
         axes:
        {
            xaxis: {
            renderer: $.jqplot.CategoryAxisRenderer,               
            ticks: [@Vars(Model.Titles.Skip(1).Select(x => string.Format("'{0}'", x.Value)))]
            }
        },
            legend: {   renderer: $.jqplot.EnhancedLegendRenderer, placement: 'outsideGrid', location:'n',  show:true    }  
         }
  );
      var w = parseInt($(".jqplot-yaxis").width(), 10) + parseInt($("#chart3").width(), 10);
var h = parseInt($(".jqplot-table-legend").height(), 10) + parseInt($(".jqplot-xaxis").height(), 10) + parseInt($("#chart3").height(), 10);
$("#chart3").width(w).height(h);
plot3.replot();
    });


</script>

<div id="chart3" style="height:300px;">
</div>

MinStat.AnalizeUI/Views/Shared/DynamicStatisticData.cshtml
@using MinStat.AnalizeUI.Models
@model IEnumerable<StatisticDataModel>
@{
    ViewBag.Title = "DynamicStatisticData";
}
@foreach (StatisticDataModel m in Model)
{
    @Html.Partial("ReportMetaData", m)
if (m != null && m.Values != null && m.Values.Any())
{
    <table class="table-striped table-bordered table-condensed">
        <tr>
            @foreach (var headItem in m.Titles)
            {
                <th>@headItem.Value
                </th>
            }
        </tr>
        @foreach (StatisticDataItemModel bodyItem in m.Values)
        {
            <tr class="@String.Format("strong{0}", bodyItem.BoldLevel)">
                <td>@Html.Raw(bodyItem.Title)
                </td>
                @foreach (string value in bodyItem.Values)
                {
                    @Html.Raw(value == "0" ? "<td class=\"muted\" style=\" text-align:center;\">" : "<td style=\" text-align:center;\">")
               
                    @value
                    @Html.Raw("</td>")
               
                }
            </tr>
        }
    </table>
    <br/><br/>
    @Html.Partial("DynamicDiagram", m)
    
}
else
{
    <strong>Данные по Вашему запросу отсутствуют.</strong>
}
}
<footer class="footer">
            Отчет составлен Информационно-аналитической системой управления балансом трудовых
            ресурсов отрасли связи, информационных технологий и массовых коммуникаций</footer>

MinStat.AnalizeUI/Views/Shared/ReportMetaData.cshtml
@model MinStat.AnalizeUI.Models.StatisticDataModel
<h1>
    Отчет</h1>
<h2>@Model.ReportName</h2>
<br />
@if (!string.IsNullOrWhiteSpace(Model.CreatedDateTime))
{
    <h3>
        Создан: <span style="font-weight: normal">@Model.CreatedDateTime</span></h3>
    <br />
}
@if (!string.IsNullOrWhiteSpace(Model.MainActivity))
{
    <h3>
        Отрасль: <span style="font-weight: normal">@Model.MainActivity</span></h3>
}
@if (!string.IsNullOrWhiteSpace(Model.Activity))
{
    <h3>
        Вид деятельности: <span style="font-weight: normal">@Html.Raw(Model.Activity)</span></h3>
}
@if (!string.IsNullOrWhiteSpace(Model.Categories))
{
    <h3>
        Категории работников: <span style="font-weight: normal">@Html.Raw(Model.Categories)</span></h3>
}
@if (!string.IsNullOrWhiteSpace(Model.FederalDistrict))
{
    <h3>
        Федеральный округ: <span style="font-weight: normal">@Model.FederalDistrict</span></h3>
}
@if (!string.IsNullOrWhiteSpace(Model.FederalSubject))
{
    <h3>
        Субъект Федерации: <span style="font-weight: normal">@Model.FederalSubject</span></h3>
}
@if (!string.IsNullOrWhiteSpace(Model.Enterprise))
{
    <h3>
        Предприятие: <span style="font-weight: normal">@Model.Enterprise</span></h3>
}
@if (!string.IsNullOrWhiteSpace(Model.StartDate))
{
    <h3>
        Начало отчетного периода: <span style="font-weight: normal">@Model.StartDate</span></h3>
}
@if (!string.IsNullOrWhiteSpace(Model.EndDate))
{
    <h3>
        Конец отчетного периода: <span style="font-weight: normal">@Model.EndDate</span></h3>
}
<br />
<br />

MinStat.AnalizeUI/Views/Shared/StaticDiagram.cshtml
@using System.Text
@using MinStat.AnalizeUI.Models
@model StatisticDataModel
@{ Model.Values = Model.Values.Where(x => x.BoldLevel == 0).ToList(); }
<script type="text/javascript" src="@Url.Content("~/Scripts//plugins/jqplot.barRenderer.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts//plugins/jqplot.categoryAxisRenderer.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts//plugins/jqplot.pointLabels.min.js")"></script>
<script type="text/javascript">
    $(document).ready(function () {

    @helper Vars(IEnumerable<string> values)
        {
            @Html.Raw(values.Aggregate((x, y) => String.Format("{0},{1}", x, y)))
    }
            @helper Series(IEnumerable<string> values)
                {
                    StringBuilder sb = new StringBuilder();
                    foreach (var value in values)
                    {
                        sb.Append(" { label: '" + value + "'  },");
                    }
            @Html.Raw(sb.ToString());
        }

   @foreach (StatisticDataItemModel dataItem in Model.Values)
   {
            @Html.Raw(String.Format("var points{0} = [];", dataItem.Id));
                                                                        foreach (string value in dataItem.Values)
                                                                        {
                @Html.Raw(String.Format("points{0}.push({1});", dataItem.Id, value.Replace(",", ".")));
                                                                        }

   }
        var plot3 = $.jqplot('chart3', [@Vars(Model.Values.Select(x => "points" + x.Id))], {
            // Tell the plot to stack the bars.    
            stackSeries: false,
            captureRightClick: false,
            series: [@Series(Model.Values.Select(x => x.Title))],
            seriesDefaults: {
                renderer: $.jqplot.BarRenderer,
                rendererOptions: {
                    barMargin: 10,
                    barWidth: 15,
                    highlightMouseDown: false
                },
                pointLabels: { show: true, location: 'n', edgeTolerance: -15 }
            },
            axes: {
                            xaxis: {
            renderer: $.jqplot.CategoryAxisRenderer,               
            ticks: [@Vars(Model.Titles.Skip(1).Select(x => string.Format("'{0}'", x.Value)))],
            min:0
            }
            },

           legend: {     renderer: $.jqplot.EnhancedLegendRenderer, placement: 'outsideGrid', location:'n',  show:true }  
        });
        $('#chart3').bind('jqplotDataClick',
            function (ev, seriesIndex, pointIndex, data) {
                $('#info3').html('series: ' + seriesIndex + ', point: ' + pointIndex + ', data: ' + data);
            });
      var w = parseInt($(".jqplot-yaxis").width(), 10) + parseInt($("#chart3").width(), 10);
var h = parseInt($(".jqplot-table-legend").height(), 10) + parseInt($(".jqplot-xaxis").height(), 10) + parseInt($("#chart3").height(), 10);
$("#chart3").width(w).height(h);
plot3.replot();
    });
</script>
<div id="chart3">
</div>

MinStat.AnalizeUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/jquery.jqplot.min.css")" rel="stylesheet" type="text/css" />
    @*    <link href="@Url.Content("~/Content/bootstrap-responsive.min.css")" rel="stylesheet" type="text/css" />*@
    <link href="@Url.Content("~/Content/datepicker.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/jquery.jqplot.min.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/excanvas.min.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-modal.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-alert.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-tooltip.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-popover.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-tab.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-dropdown.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-scrollspy.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-datepicker.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/Bonch.AnalizeUI.Info.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/Bonch.AnalizeUI.Reports.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/Bonch.AnalizeUI.Checkboxes.js")" type="text/javascript" ></script>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar">
                                                                                </span>
                </button>
                @Html.ActionLink("Кадры", "Index", "Home", null, new { @class = "brand" })
                <div class="nav">
                    <ul class="nav">
                        <li class="dropdown">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown">Стандартные отчеты<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a data-toggle="modal" href="#chooseEnterpriseModal">Предприятие</a></li>
                                <li><a data-toggle="modal" href="#chooseFederalSubjectModal">Субъект Федерации</a></li>
                                <li><a data-toggle="modal" href="#chooseFederalDistrictModal">Федеральный округ</a></li>
                                <li class="divider"></li>
                                <li><a data-toggle="modal" href="#chooseActivityModal">Вид деятельности</a></li>
                                <li class="divider"></li>
                                <li><a href="#">@Html.ActionLink("Отрасль в целом", "Report", "Common")</a></li>
                            </ul>
                        </li>
                        <li class='@ViewBag.FullReport'>
                            @Html.ActionLink("Базовый отчет", "Index", "FullReport")
                        </li>
                        <li class='@ViewBag.Consolidate'>
                            @Html.ActionLink("Сводный отчет", "Index", "Consolidate")
                        </li>
                        <li class='@ViewBag.Summary'>
                            @Html.ActionLink("Количественный отчет", "Index", "Summary")
                        </li>
                        <li class='@ViewBag.Administration'>
                            @Html.ActionLink("Добавить предприятие", "Index", "Administration")
                        </li>
                         <li class='@ViewBag.Help'>
                            @Html.ActionLink("Справка", "Index", "Help")
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <br />
    <br />
    <br />
    <div class="container">
        <div class="row">
            <div class="span12">
                @RenderBody()
            </div>
        </div>

    </div>
    @Html.Action("Chooser", "Common")
</body>
</html>