MinStat.Enterprises.WebUI/Controllers/HelpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinStat.Enterprises.WebUI.Controllers
{
    [Authorize]
    public class HelpController : Controller
    {
        //
        // GET: /Help/

        public ActionResult Index()
        {
            return View();
        }

    }
}

MinStat.Enterprises.WebUI/Controllers/SummariesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MinStat.Enterprises.WebUI.Filters;
using MinStat.Enterprises.WebUI.ServiceAdapters;
using MinStat.Enterprises.WebUI.Models;

namespace MinStat.Enterprises.WebUI.Controllers
{
    [Authorize, NoCache]
    public class SummariesController : Controller
    {
        //
        // GET: /Summaries/
        private IEnterpriseServiceAdapter _serviceAdapter;
        private string _enterpriseName;

        public SummariesController(IEnterpriseServiceAdapter serviceAdapter)
        {
            _serviceAdapter = serviceAdapter;
            //ToDo: Разобраться, почему не ловится ошибка.
            try
            {
                _enterpriseName = _serviceAdapter.GetEnterpriseName();
                ViewBag.EnterpriseName = _enterpriseName;
                ViewBag.FederalSubjectName = _serviceAdapter.GetFederalSubjectName();
                ViewBag.FederalDistrictName = _serviceAdapter.GetFederalDistrictName();
            }
            catch(Exception)
            {}
        }

        public SummariesController()
            : this(new EnterpriseServiceAdapter())
        {
        }

        public ActionResult Index()
        {
            IEnumerable<SummaryModel> model = _serviceAdapter.GetSummaries();
            ViewBag.Activities = _serviceAdapter.GetActivities();
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Create(SummaryModel summary)
        {
            if (!String.IsNullOrWhiteSpace(summary.Title))
            {
                if (summary.Id > 0)
                {
                    _serviceAdapter.UpdateSummary(summary.Id, summary.Title, summary.Activities);
                }
                else
                {
                    _serviceAdapter.CreateSummary(summary.Title, summary.Activities);

                }
            }
            else
            {
                ModelState.AddModelError("", "Укажите название отчета.");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Remove(int summaryId)
        {
            _serviceAdapter.RemoveSummary(summaryId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Copy(string Title, int summaryId)
        {
            _serviceAdapter.CopySummary(Title, summaryId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Publish(int summaryId)
        {
            _serviceAdapter.PublishSummary(summaryId);
            return RedirectToAction("Index");
        }

        public JsonResult Activities(int summaryId)
        {
            IEnumerable<ActivityModel> activities = _serviceAdapter.GetActivities(summaryId);
            return Json(activities, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> fileUpload, int summaryId)
        {
            try
            {
                foreach (var file in fileUpload)
                {
                    if (file == null) continue;

                    byte[] fileByteArray = new byte[file.InputStream.Length];
                    file.InputStream.Read(fileByteArray, 0, fileByteArray.Length);
                    _serviceAdapter.UploadPersons(fileByteArray, summaryId);
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("uploadfail", "При загрузке файла произошла ошибка. Проверьте загружаемый файл на валидность данных.");
                return Index();
            }

        }

    }
}

MinStat.Enterprises.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    @*    <link href="@Url.Content("~/Content/bootstrap-responsive.min.css")" rel="stylesheet" type="text/css" />*@
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/jquery.jqplot.min.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/excanvas.min.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-modal.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-alert.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-tooltip.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-popover.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-tab.js")" type="text/javascript" ></script>
    <script src="@Url.Content("~/Scripts/bootstrap-dropdown.js")" type="text/javascript" ></script>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar">
                    </span>
                </button>
                @Html.ActionLink("Подготовка отчетов", "Index", "Summaries", null, new { @class = "brand" })
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        @if (HttpContext.Current.User.Identity.IsAuthenticated)
                        {
                            <li class="">@Html.ActionLink("Справка", "Index", "Help")</li>
                        }
                    </ul>
                    @if (HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        <p class="navbar-text pull-right">
                            @Html.Raw(String.Format("Здравствуйте,{0} &nbsp; &nbsp;| &nbsp; &nbsp;", HttpContext.Current.User.Identity.Name))
                            @Html.ActionLink("Выйти", "LogOff", "Account")
                        </p>
                    }
                </div>
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
    <div class="container">
        <div class="row">
            <div class="span12">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>